### ISSUE TITLE
Print updates fail on undefined constants

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/print#19]
I think this is PHP 8+ only. The updates die on these. The install files don't load .module so none of the constants are recognized. It's okay to use the item defined in the update hook.

**Comment by herbdool** [comment]
@laryn I've got a PR for this issue and for #20: https://github.com/backdrop-contrib/print/pull/21

**Comment by laryn** [comment]
I merged your fix -- thanks @herbdool!
