### ISSUE TITLE
Remove Remove the use of jQuery load() method to handle load events

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/print#31]
This module uses the jquery method load() to handle the load event in `print.pages.inc`. This method was deprecated, and causes Javascript to crash when used with jQuery 3, which is now the default for Backdrop.

The use of the event handler load(function(){}) should be converted to on('load', function(){})

**Comment by laryn** [comment]
@argiepiano This module is still messy in a lot of places, but I don't think I'm using it anywhere and don't have free time to do more than just patch this immediate issue -- care to test the PR and see if it fixes the problem on your end?

**Comment by argiepiano** [comment]
@laryn I've tested and the PR does fix the problem. Thanks!

**Comment by laryn** [comment]
Thanks!
