### ISSUE TITLE
Drupal print module marked unsupported

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/print#7]
Today (Jan 26th, 2022) the Drupal Print module was marked unsupported.

I have offered to co-maintain the Print module for Drupal 7 in the hopes that I can help fix and/or test the solution to the unresolved security issue. 

@laryn as the maintainer of the Backdrop CMS version of print, I'm hoping that we can coordinate this release with Drupal's.

**Comment by laryn** [comment]
Thanks @jenlampton -- sounds great.

**Comment by jenlampton** [comment]
@laryn a release for the Drupal print module will be coming out soon (pending Drupal security team approval). I have a copy of the patch if you'd like to get it ready before then, but please do not push anything into any public location before then.

**Comment by jenlampton** [comment]
I have applied the patch as the last commit in https://github.com/jenlampton/print-private and sent you an invite.

**Comment by laryn** [comment]
Thanks @jenlampton I was able to get the patch and merge it locally. Early testing on functionality seems fine.

**Comment by jenlampton** [comment]
New versions released, and issue summary copied over to the public issue https://www.drupal.org/node/3283295

2.3: https://www.drupal.org/project/print/releases/7.x-2.3
2.4: https://www.drupal.org/project/print/releases/7.x-2.4

**Comment by laryn** [comment]
@jenlampton 
I still don't have an actual release for Backdrop but I've tried to merge in the upstream changes here.
